



// RESULTS CONTROL BAR
export const RESULTS_LAYOUT_STYLE_CARD = 'CARD';
export const RESULTS_LAYOUT_STYLE_LIST = 'LIST';
export const TRIGGER_RESULTS_LAYOUT_STYLE_CARD = 'TRIGGER_RESULTS_LAYOUT_STYLE_CARD';
export const TRIGGER_RESULTS_LAYOUT_STYLE_LIST = 'TRIGGER_RESULTS_LAYOUT_STYLE_LIST';